name: image_bundler
description: A Flutter tool that bundles a collection of input images as responsive images.
version: 1.0.0
repository: https://github.com/aloisdeniel/image_bundler/packages/image_bundler

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  image: ^4.5.4
  path: ^1.9.1
  recase: ^4.1.0
  vector_graphics_compiler: ^1.1.17

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  image_bundler:
